CREATE VIEW VSTAFAC2 (PROJNO, ACTNO, ACTDESC, EMPNO, FIRSTNME, MIDINIT, LASTNAME, EMPTIME, STDATE, ENDATE, TYPE) AS
SELECT ALL EP.PROJNO,
           EP.ACTNO,
           AC.ACTDESC,
           EP.EMPNO,
           EM.FIRSTNME,
           EM.MIDINIT,
           EM.LASTNAME,
           EP.EMPTIME,
           EP.EMSTDATE,
           EP.EMENDATE,
           '2'
FROM EMPPROJACT EP,
     ACT AC,
     EMP EM
WHERE EP.ACTNO = AC.ACTNO
  AND EP.EMPNO = EM.EMPNO;


SELECT *
FROM VSTAFAC2
;

SELECT PROJNO, ACTNO, STDATE, COUNT(1)
FROM VSTAFAC2
GROUP BY PROJNO, ACTNO, STDATE
HAVING COUNT(1) > 1
;